version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
